package Hibernate;
// Generated Nov 23, 2016 2:43:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private String nid;
     private String namados;
     private String telahdos;
     private Date talahdos;
     private String alamatdos;
     private String jkdos;
     private String npdos;

    public Dosen() {
    }

	
    public Dosen(String nid, String namados, String telahdos, Date talahdos, String alamatdos) {
        this.nid = nid;
        this.namados = namados;
        this.telahdos = telahdos;
        this.talahdos = talahdos;
        this.alamatdos = alamatdos;
    }
    public Dosen(String nid, String namados, String telahdos, Date talahdos, String alamatdos, String jkdos, String npdos) {
       this.nid = nid;
       this.namados = namados;
       this.telahdos = telahdos;
       this.talahdos = talahdos;
       this.alamatdos = alamatdos;
       this.jkdos = jkdos;
       this.npdos = npdos;
    }
   
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getNamados() {
        return this.namados;
    }
    
    public void setNamados(String namados) {
        this.namados = namados;
    }
    public String getTelahdos() {
        return this.telahdos;
    }
    
    public void setTelahdos(String telahdos) {
        this.telahdos = telahdos;
    }
    public Date getTalahdos() {
        return this.talahdos;
    }
    
    public void setTalahdos(Date talahdos) {
        this.talahdos = talahdos;
    }
    public String getAlamatdos() {
        return this.alamatdos;
    }
    
    public void setAlamatdos(String alamatdos) {
        this.alamatdos = alamatdos;
    }
    public String getJkdos() {
        return this.jkdos;
    }
    
    public void setJkdos(String jkdos) {
        this.jkdos = jkdos;
    }
    public String getNpdos() {
        return this.npdos;
    }
    
    public void setNpdos(String npdos) {
        this.npdos = npdos;
    }




}


