package Hibernate;
// Generated Nov 23, 2016 2:43:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private String namamhs;
     private String fakultas;
     private String prodi;
     private String telahmhs;
     private Date talahmhs;
     private String jkmhs;
     private String statusmhs;
     private String alamatmhs;
     private String npmhs;

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim, String namamhs, String fakultas, String prodi, String telahmhs, Date talahmhs, String jkmhs, String statusmhs, String alamatmhs) {
        this.nim = nim;
        this.namamhs = namamhs;
        this.fakultas = fakultas;
        this.prodi = prodi;
        this.telahmhs = telahmhs;
        this.talahmhs = talahmhs;
        this.jkmhs = jkmhs;
        this.statusmhs = statusmhs;
        this.alamatmhs = alamatmhs;
    }
    public Mahasiswa(String nim, String namamhs, String fakultas, String prodi, String telahmhs, Date talahmhs, String jkmhs, String statusmhs, String alamatmhs, String npmhs) {
       this.nim = nim;
       this.namamhs = namamhs;
       this.fakultas = fakultas;
       this.prodi = prodi;
       this.telahmhs = telahmhs;
       this.talahmhs = talahmhs;
       this.jkmhs = jkmhs;
       this.statusmhs = statusmhs;
       this.alamatmhs = alamatmhs;
       this.npmhs = npmhs;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getNamamhs() {
        return this.namamhs;
    }
    
    public void setNamamhs(String namamhs) {
        this.namamhs = namamhs;
    }
    public String getFakultas() {
        return this.fakultas;
    }
    
    public void setFakultas(String fakultas) {
        this.fakultas = fakultas;
    }
    public String getProdi() {
        return this.prodi;
    }
    
    public void setProdi(String prodi) {
        this.prodi = prodi;
    }
    public String getTelahmhs() {
        return this.telahmhs;
    }
    
    public void setTelahmhs(String telahmhs) {
        this.telahmhs = telahmhs;
    }
    public Date getTalahmhs() {
        return this.talahmhs;
    }
    
    public void setTalahmhs(Date talahmhs) {
        this.talahmhs = talahmhs;
    }
    public String getJkmhs() {
        return this.jkmhs;
    }
    
    public void setJkmhs(String jkmhs) {
        this.jkmhs = jkmhs;
    }
    public String getStatusmhs() {
        return this.statusmhs;
    }
    
    public void setStatusmhs(String statusmhs) {
        this.statusmhs = statusmhs;
    }
    public String getAlamatmhs() {
        return this.alamatmhs;
    }
    
    public void setAlamatmhs(String alamatmhs) {
        this.alamatmhs = alamatmhs;
    }
    public String getNpmhs() {
        return this.npmhs;
    }
    
    public void setNpmhs(String npmhs) {
        this.npmhs = npmhs;
    }




}


