package Hibernate;
// Generated Nov 23, 2016 2:43:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private String username;
     private String namamem;
     private String telahmem;
     private Date talahmem;
     private String password;

    public Member() {
    }

    public Member(String username, String namamem, String telahmem, Date talahmem, String password) {
       this.username = username;
       this.namamem = namamem;
       this.telahmem = telahmem;
       this.talahmem = talahmem;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getNamamem() {
        return this.namamem;
    }
    
    public void setNamamem(String namamem) {
        this.namamem = namamem;
    }
    public String getTelahmem() {
        return this.telahmem;
    }
    
    public void setTelahmem(String telahmem) {
        this.telahmem = telahmem;
    }
    public Date getTalahmem() {
        return this.talahmem;
    }
    
    public void setTalahmem(Date talahmem) {
        this.talahmem = talahmem;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


